import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blogy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex items-center justify-between p-2 bg-blue-600 text-white">
          <Link href={"/"} className="text-3xl font-bold ">
            BLOGY
          </Link>
          <Link
            href={"/create"}
            className="p-2 text-blue-600 bg-white rounded-md font-medium text-sm"
          >
            Creat new blog
          </Link>
        </nav>
        <div className="px-2">{children}</div>
      </body>
    </html>
  );
}
